python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet18 --batch-size=512 | tee out-extraforward-resnet18-512
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet18 --batch-size=256 | tee out-extraforward-resnet18-256
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet18 --batch-size=128 | tee out-extraforward-resnet18-128
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet18 --batch-size=64 | tee out-extraforward-resnet18-64
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet18 --batch-size=32 | tee out-extraforward-resnet18-32
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet50 --batch-size=512 | tee out-extraforward-resnet50-512
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet50 --batch-size=256 | tee out-extraforward-resnet50-256
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet50 --batch-size=128 | tee out-extraforward-resnet50-128
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet50 --batch-size=64 | tee out-extraforward-resnet50-64
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet50 --batch-size=32 | tee out-extraforward-resnet50-32
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet101 --batch-size=512 | tee out-extraforward-resnet101-512
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet101 --batch-size=256 | tee out-extraforward-resnet101-256
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet101 --batch-size=128 | tee out-extraforward-resnet101-128
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet101 --batch-size=64 | tee out-extraforward-resnet101-64
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=resnet101 --batch-size=32 | tee out-extraforward-resnet101-32
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet121 --batch-size=512 | tee out-extraforward-densenet121-512
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet121 --batch-size=256 | tee out-extraforward-densenet121-256
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet121 --batch-size=128 | tee out-extraforward-densenet121-128
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet121 --batch-size=64 | tee out-extraforward-densenet121-64
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet121 --batch-size=32 | tee out-extraforward-densenet121-32
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet201 --batch-size=512 | tee out-extraforward-densenet201-512
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet201 --batch-size=256 | tee out-extraforward-densenet201-256
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet201 --batch-size=128 | tee out-extraforward-densenet201-128
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet201 --batch-size=64 | tee out-extraforward-densenet201-64
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=densenet201 --batch-size=32 | tee out-extraforward-densenet201-32
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_0 --batch-size=512 | tee out-extraforward-squeezenet1_0-512
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_0 --batch-size=256 | tee out-extraforward-squeezenet1_0-256
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_0 --batch-size=128 | tee out-extraforward-squeezenet1_0-128
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_0 --batch-size=64 | tee out-extraforward-squeezenet1_0-64
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_0 --batch-size=32 | tee out-extraforward-squeezenet1_0-32
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_1 --batch-size=512 | tee out-extraforward-squeezenet1_1-512
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_1 --batch-size=256 | tee out-extraforward-squeezenet1_1-256
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_1 --batch-size=128 | tee out-extraforward-squeezenet1_1-128
#python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_1 --batch-size=64 | tee out-extraforward-squeezenet1_1-64
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=squeezenet1_1 --batch-size=32 | tee out-extraforward-squeezenet1_1-32
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=inceptionv3 --batch-size=512 | tee out-extraforward-inceptionv3-512
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=inceptionv3 --batch-size=256 | tee out-extraforward-inceptionv3-256
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=inceptionv3 --batch-size=128 | tee out-extraforward-inceptionv3-128
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=inceptionv3 --batch-size=64 | tee out-extraforward-inceptionv3-64
python -u main.py /proj/BigLearning/ahjiang/datasets/imagenet-data --arch=inceptionv3 --batch-size=32 | tee out-extraforward-inceptionv3-32
